const VALUES = [
  { id:1,  ja:"受容",             en:"Acceptance",   desc:"自分自身や他者を、あるがままに受け入れること" },
  { id:2,  ja:"正確さ",           en:"Accuracy",     desc:"正確であること、細部まで注意を払うこと" },
  { id:3,  ja:"達成",             en:"Achievement",  desc:"目標を成功裏に成し遂げること" },
  { id:4,  ja:"冒険",             en:"Adventure",    desc:"新しい刺激的な経験を求めること" },
  { id:5,  ja:"愛情",             en:"Affection",    desc:"愛情深い気持ちを示したり受け取ったりすること" },
  { id:6,  ja:"野心",             en:"Ambition",     desc:"強く成功したい、権力を持ちたいと願うこと" },
  { id:7,  ja:"自己主張",         en:"Assertiveness",desc:"自分の考えや権利を自信をもって表明すること" },
  { id:8,  ja:"自律",             en:"Autonomy",     desc:"自分で決定を下し、行動する自由" },
  { id:9,  ja:"美",               en:"Beauty",       desc:"周囲の美しさを評価したり創造したりすること" },
  { id:10, ja:"思いやり",         en:"Caring",       desc:"他者の幸福に関心を持ち、サポートすること" },
  { id:11, ja:"挑戦",             en:"Challenge",    desc:"困難な課題に取り組む機会" },
  { id:12, ja:"変化",             en:"Change",       desc:"新しさ、多様性、既存のものからの移行を求めること" },
  { id:13, ja:"快適さ",           en:"Comfort",      desc:"身体的または精神的に楽な状態であること" },
  { id:14, ja:"献身",             en:"Commitment",   desc:"目的、人、あるいは行動に専念すること" },
  { id:15, ja:"共同体",           en:"Community",    desc:"所属する集団や地域社会と繋がり、貢献すること" },
  { id:16, ja:"共感",             en:"Compassion",   desc:"他者の苦痛を理解し、和らげたいと願うこと" },
  { id:17, ja:"能力",             en:"Competence",   desc:"特定の分野で効果的に行動できること" },
  { id:18, ja:"競争",             en:"Competition",  desc:"他者と対抗し、優位に立とうとすること" },
  { id:19, ja:"貢献",             en:"Contribution", desc:"他者や大義のために何か役立つことをすること" },
  { id:20, ja:"協力",             en:"Cooperation",  desc:"他者と協力して共通の目標を達成すること" },
  { id:21, ja:"創造性",           en:"Creativity",   desc:"新しいアイデアや方法を生み出すこと" },
  { id:22, ja:"信頼性",           en:"Dependability",desc:"頼りになり、一貫性があり、約束を守ること" },
  { id:23, ja:"尊厳",             en:"Dignity",      desc:"尊重され、自尊心を持つこと" },
  { id:24, ja:"義務",             en:"Duty",         desc:"期待されることや、必要とされることを行うこと" },
  { id:25, ja:"環境保全",         en:"Ecology",      desc:"自然環境と地球の健康を保護すること" },
  { id:26, ja:"平等",             en:"Equality",     desc:"全ての人々が同じ権利や機会を持つこと" },
  { id:27, ja:"興奮",             en:"Excitement",   desc:"刺激的で、活気に満ちた経験" },
  { id:28, ja:"公正さ",           en:"Fairness",     desc:"偏見なく、道徳的かつ正当に行動すること" },
  { id:29, ja:"信念",             en:"Faith",        desc:"宗教的、または精神的な信条を持つこと" },
  { id:30, ja:"家族",             en:"Family",       desc:"家族との関係や時間を大切にすること" },
  { id:31, ja:"柔軟性",           en:"Flexibility",  desc:"状況や環境の変化に容易に適応できること" },
  { id:32, ja:"許し",             en:"Forgiveness",  desc:"他者や自分自身の間違いを水に流すこと" },
  { id:33, ja:"自由",             en:"Freedom",      desc:"制限なく行動し、選択できること" },
  { id:34, ja:"友情",             en:"Friendship",   desc:"親しい友人との関係を築き、維持すること" },
  { id:35, ja:"楽しみ",           en:"Fun",          desc:"遊び心や喜びを感じる活動に従事すること" },
  { id:36, ja:"寛大さ",           en:"Generosity",   desc:"時間、資源、富などを惜しみなく与えること" },
  { id:37, ja:"成長",             en:"Growth",       desc:"精神的、個人的、スキル面での発展を追求すること" },
  { id:38, ja:"健康",             en:"Health",       desc:"身体的、精神的によい状態を維持すること" },
  { id:39, ja:"助けになること",   en:"Helpfulness",  desc:"他者のニーズをサポートし、援助を提供すること" },
  { id:40, ja:"正直さ",           en:"Honesty",      desc:"真実を話し、誠実に行動すること" },
  { id:41, ja:"希望",             en:"Hope",         desc:"良い未来を信じ、楽観的であること" },
  { id:42, ja:"謙虚さ",           en:"Humility",     desc:"傲慢でなく、自分の限界や他者の価値を認めること" },
  { id:43, ja:"ユーモア",         en:"Humor",        desc:"面白いものを見つけたり、笑いを楽しんだりすること" },
  { id:44, ja:"独立",             en:"Independence", desc:"他者に頼らず、自分自身でいること" },
  { id:45, ja:"内面の平和",       en:"Inner Peace",  desc:"心が穏やかで、静寂であること" },
  { id:46, ja:"インスピレーション",en:"Inspiration", desc:"自分や他者をやる気にさせ、創造性を刺激すること" },
  { id:47, ja:"誠実",             en:"Integrity",    desc:"強い道徳的原則を持ち、それに従うこと" },
  { id:48, ja:"親密さ",           en:"Intimacy",     desc:"他者との深く、感情的に結びついた関係" },
  { id:49, ja:"正義",             en:"Justice",      desc:"道徳的権利に基づいて行動し、公平な扱いを支持すること" },
  { id:50, ja:"親切",             en:"Kindness",     desc:"温かく、思いやりのある態度で他者に接すること" },
  { id:51, ja:"知識",             en:"Knowledge",    desc:"学び、理解を深めること" },
  { id:52, ja:"指導力",           en:"Leadership",   desc:"他者を導き、影響を与え、方向付ける能力" },
  { id:53, ja:"愛",               en:"Love",         desc:"他者への深く、温かい感情的な愛着" },
  { id:54, ja:"忠誠心",           en:"Loyalty",      desc:"人、グループ、信念に対する献身的な支援" },
  { id:55, ja:"習熟",             en:"Mastery",      desc:"特定のスキルや知識において高度なレベルに達すること" },
  { id:56, ja:"意味",             en:"Meaning",      desc:"人生や活動に目的や重要性があると感じること" },
  { id:57, ja:"節度",             en:"Moderation",   desc:"極端な行動や感情を避け、バランスを保つこと" },
  { id:58, ja:"自然",             en:"Nature",       desc:"自然界との繋がりや、その美しさを大切にすること" },
  { id:59, ja:"秩序",             en:"Order",        desc:"整理され、予測可能で、規則に従っている状態" },
  { id:60, ja:"忍耐",             en:"Patience",     desc:"困難や遅延に冷静に対処できること" },
  { id:61, ja:"喜び",             en:"Pleasure",     desc:"感覚的な満足や楽しみを経験すること" },
  { id:62, ja:"権力",             en:"Power",        desc:"他者や状況をコントロールし、影響を与える能力" },
  { id:63, ja:"今にいること",     en:"Presence",     desc:"今この瞬間に意識を集中させること" },
  { id:64, ja:"プライバシー",     en:"Privacy",      desc:"自分自身の空間や情報をコントロールできること" },
  { id:65, ja:"思慮深さ",         en:"Prudence",     desc:"将来を考慮して慎重に行動すること" },
  { id:66, ja:"承認",             en:"Recognition",  desc:"自分の業績や価値が他者から認められること" },
  { id:67, ja:"責任",             en:"Responsibility",desc:"自分の行動の結果に対して責任を負うこと" },
  { id:68, ja:"尊敬",             en:"Respect",      desc:"他者や自分自身を大切に思い、価値を認めること" },
  { id:69, ja:"安全",             en:"Safety",       desc:"危険や脅威から守られている状態" },
  { id:70, ja:"安定",             en:"Security",     desc:"経済的、感情的、物理的な安定性を保つこと" },
  { id:71, ja:"自制心",           en:"Self-Control", desc:"自分の感情や衝動を管理し、統制できること" },
  { id:72, ja:"自己表現",         en:"Self-Expression",desc:"感情、考え、個性を創造的に伝えること" },
  { id:73, ja:"官能",             en:"Sensuality",   desc:"五感を通じて喜びや満足を経験すること" },
  { id:74, ja:"奉仕",             en:"Service",      desc:"他者のニーズに応えるために行動すること" },
  { id:75, ja:"セクシュアリティ", en:"Sexuality",    desc:"自分の性的なアイデンティティや関係性を尊重すること" },
  { id:76, ja:"簡素",             en:"Simplicity",   desc:"不必要なものを避け、生活を単純に保つこと" },
  { id:77, ja:"技能",             en:"Skill",        desc:"特定の作業や活動を行うための能力" },
  { id:78, ja:"孤独",             en:"Solitude",     desc:"邪魔されずに一人でいる時間" },
  { id:79, ja:"精神性",           en:"Spirituality", desc:"人生におけるより深い、非物質的な目的を探求すること" },
  { id:80, ja:"安定性",           en:"Stability",    desc:"一貫性を保ち、変化に動じないこと" },
  { id:81, ja:"成功",             en:"Success",      desc:"目的を達成したり、社会的な地位を得たりすること" },
  { id:82, ja:"支援",             en:"Support",      desc:"他者に、助け・励まし・援助を提供すること" },
  { id:83, ja:"チームワーク",     en:"Teamwork",     desc:"協調して集団で働くこと" },
  { id:84, ja:"寛容",             en:"Tolerance",    desc:"自分と異なる意見や行動を受け入れること" },
  { id:85, ja:"伝統",             en:"Tradition",    desc:"文化や家族の習慣や信念を尊重し、維持すること" },
  { id:86, ja:"信頼",             en:"Trust",        desc:"他者や状況に対して確信を持つこと" },
  { id:87, ja:"真実",             en:"Truth",        desc:"正確で、誠実で、現実に基づいていること" },
  { id:88, ja:"理解",             en:"Understanding",desc:"情報、人々、状況について深い洞察を持つこと" },
  { id:89, ja:"多様性",           en:"Variety",      desc:"変化に富んだ経験や選択肢を持つこと" },
  { id:90, ja:"富",               en:"Wealth",       desc:"経済的な豊かさ、または十分な資源を持つこと" },
  { id:91, ja:"知恵",             en:"Wisdom",       desc:"経験、知識、優れた判断力を使って行動すること" },
];

const CATS = {
  very:     { label: "とても大切",      icon: "◆", color: "#e08050" },
  somewhat: { label: "まあまあ大切",    icon: "◇", color: "#c0a040" },
  not:      { label: "あまり大切でない", icon: "○", color: "#6a9a80" },
};

const CAT_KEYS = ["very", "somewhat", "not"];
